### ISSUE TITLE
Add zserio_compatibility_version introduced in zserio 2.5.0

### ISSUE THREAD

**Issue by Mi-La** [4og/zserio-language-support#1]
Please note that a new [language directive](http://zserio.org/doc/ZserioLanguageOverview.html#compatibility-check) `zserio_compatibility_version` was added in zserio 2.5.0.

**Comment by 4og** [comment]
Thanks. This is fixed in 3d8f0d3e64ea71d608874a256183e98c6ca30c51
I'm going to make a new release later today.

**Comment by 4og** [comment]
The `zserio_compatibility_version` is now available in the 0.5.0 release.
